### ISSUE TITLE
Invalid dataset specification

### ISSUE THREAD

**Issue by zdaiot** [alekseynp/kaggle-dev-ops#1]
Hello, when I run to `SUBMISSION=file.csv make release-csv` according to your instructions, the following error occurred.

```
rm -rf submission_csv
mkdir -p submission_csv
cp kernel-csv-metadata.json submission_csv/kernel-metadata.json
cp dataset-csv-metadata.json submission_csv/dataset-metadata.json
cp kernel_csv.py submission_csv/kernel.py
cp file.csv submission_csv/out.csv
kaggle datasets version -m "file.csv" -p submission_csv -r tar
sleep 10s
kaggle kernels push -p submission_csv/
Starting upload for file kernel.py
100%|██████████████████████████████████████████████████████████████████| 413/413 [00:07<00:00, 53.1B/s]
Upload successful: kernel.py (413B)
Starting upload for file out.csv
100%|█████████████████████████████████████████████████████████████| 1.06M/1.06M [00:12<00:00, 89.1kB/s]
Upload successful: out.csv (1MB)
Dataset version is being created. Please check progress at https://www.kaggle.com/zdaiot/severstal_csv_submission
Invalid dataset specification /severstal_csv_submission
Makefile:34: recipe for target 'release-csv' failed
make: *** [release-csv] Error 1
```

What should I do？

**Comment by alekseynp** [comment]
It looks like something when wrong when the `init-csv-submission` script tried to read your kaggle username. What happens when you run `kaggle config view`? Did you run `init-csv-submission` before configuring the kaggle cli?

As a workaround, you should be able to manually edit the `kernel-csv-metadata.json` and add your username here:
`"dataset_sources": ["YOUR_KAGGLE_USERNAME_HERE_CURRENTLY_BLANK_DUE_TO_BUG/severstal_csv_submission"],`

**Comment by zdaiot** [comment]
Thanks a lot，I ran `init-csv-submission` before configuring the kaggle cli.
I solved it through change `"dataset_sources"` in kernel-csv-metadata.json

**Comment by arthurnage** [comment]
I have the same issue. Even though kaggle config view prints by nickname out, it doesn't appear in """USERNAME=$(kaggle config view | grep username:* | cut -c 13-)""" line in Makefile.
I put a little of my mind into it and I've still got no clue why it happens.
